# Generated by Django 5.2.13 on 2026-07-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="verb",
            field=models.CharField(
                choices=[
                    ("added_to_event", "Added to event"),
                    ("removed_from_event", "Removed from event"),
                    ("time_frame_changed", "Time frame changed"),
                ],
                max_length=50,
            ),
        ),
    ]
