# Generated by Django 6.0.7 on 2026-08-13 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def set_manager_to_creator(apps, schema_editor):
    Event = apps.get_model("dashboard", "Event")
    Event.objects.filter(manager__isnull=True).update(manager=F("creator"))


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_userprofile_bio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="manager",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managed_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            set_manager_to_creator, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="event",
            name="manager",
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=models.CASCADE,
                related_name="managed_events",
            ),
        ),
    ]
