# Generated by Django 5.1.15 on 2026-01-29 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("starting_date", models.DateTimeField()),
                ("ending_date", models.DateTimeField()),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True, related_name="project", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
