# Generated by Django 5.2.13 on 2026-07-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="earnings",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="earnings_received",
            field=models.BooleanField(default=False),
        ),
    ]
