# Generated by Django 5.2.13 on 2026-07-12 18:08

from django.conf import settings
from django.db import migrations


def create_profiles(apps, schema_editor):
    User = apps.get_model(
        settings.AUTH_USER_MODEL if False else "auth", "User"
    )  # see note below
    UserProfile = apps.get_model("abi", "UserProfile")

    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)


def reverse_noop(apps, schema_editor):
    pass  # nothing to undo, or delete profiles if you want strict reversibility


class Migration(migrations.Migration):
    dependencies = [
        ("abi", "0003_remove_abikasse_current_and_more"),
    ]

    operations = [
        migrations.RunPython(create_profiles, reverse_noop),
    ]
