# Generated by Django 5.2.13 on 2026-06-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abi", "0006_alter_abikasse_current"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="final",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
